routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('users', 'UsersController');

//Route::group(['middleware' => 'web', 'prefix' => 'users'], function () {
//    Route::get('/', 'UsersController@index')->name('users');
////    Route::get('/users/{id}', 'UsersController@show');
//    Route::get('/{id}/edit', 'UsersController@edit')->name('users.edit');
//    Route::patch('/{id}', 'UsersController@update')->name('users.update');
//});

Route::group(['middleware' => ['web']], function () {
    Route::get('/categories', 'CategoriesController@index')->name('categories');
    Route::get('/category-products/{category}', 'CategoryProductsController@show')->name('categories.show');
    Route::get('/products', 'ProductsController@show')->name('categories.show');
    Route::post('/categories', 'CategoriesController@store')->name('categories.store');

    Route::get('categories/{category}', 'CategoryProductsController@show');
    Route::patch('/categories/{category}', 'CategoriesController@update')->name('categories.update');
    Route::delete('categories/{category}', 'CategoriesController@destroy')->name('categories.destroy');


    Route::group(['middleware' => ['web', 'role:admin']], function () {
        Route::get('/categories/create', 'CategoriesController@create')->name('categories.create');
        Route::get('/categories/{category}/edit', 'CategoriesController@edit')->name('categories.edit');
    });

});

Route::group(['middleware' => ['web'], 'prefix' => 'dashboard'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
});

Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'products'], function () {
    Route::get('/', 'ProductsController@index')->name('products');
    Route::get('/create', 'ProductsController@create')->name('products.create');
    Route::post('/', 'ProductsController@store')->name('products.store');
    Route::get('/{product}/edit', 'ProductsController@edit')->name('products.edit');
    Route::patch('/{product}', 'ProductsController@update')->name('products.update');
    Route::delete('/{product}', 'ProductsController@destroy')->name('products.destroy');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Category;

class Product extends Model
{
    protected $fillable = [
        'status',
        'name',
        'category_id',
        'size',
        'price',
    ];
    protected  $hidden = [];

    const sortable = ['id', 'name', 'size', 'price'];
    const countRecords = ['2','10','15','20'];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function getAvailabilityAttribute()
    {
        return $this->status ? 'Availability' : 'Not available';
    }

    public function scopeSearch($query, $q, string $searchable)
    {

        if($q == null) {
            return $query;
        }

        return $query
            ->where($searchable, 'LIKE', "%{$q}%");
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\product\FieldRequestCreate;
use App\Http\Requests\product\FieldRequestUpdate;
use App\Product;
use App\User;
use Illuminate\Http\Request;
use PhpParser\Builder;

class ProductsController extends Controller
{

    public function index(Request $request, Product $product)
    {
        $categoryIdSelected = [];
        if ($request->has('category_id')) {
            $categoryIdSelected = $request->query('category_id');
        }
        $productsDates = $this->formFilter($request, $categoryIdSelected);

        return view('product.index',
            [
                'products' => $productsDates['products'],
                'orderBy' => $productsDates['orderBy'],
                'sortBy' => $productsDates['sortBy'],
                'q' => $productsDates['q'],
                'perPage' => $productsDates['perPage'],
                'sortable' => Product::sortable,
                'countRecords' => Product::countRecords,
                'categories' => Category::all(),
                'categoryIdSelected' => $categoryIdSelected
        ]);
    }

    public function formFilter($request, $categoryIdSelected = [])
    {
        $sortBy = 'id';
        $orderBy = 'desc';
        $perPage = 5;
        $q = null;

        if ($request->has('orderBy')) $orderBy = $request->query('orderBy');
        if ($request->has('price_start')) $price['price_start'] = $request->query('price_start');
        if ($request->has('price_end')) $price['price_end'] = $request->query('price_end');

        if ($request->has('sortBy')) $sortBy = $request->query('sortBy');
        if ($request->has('perPage')) $perPage = $request->query('perPage');
        if ($request->has('q')) $q = $request->query('q');

        $products = Product::with(['category'])

            ->whereIn('category_id', $categoryIdSelected)
            ->search($q, $sortBy)
            ->orderBy($sortBy, $orderBy)
            ->paginate($perPage)
            ->appends(request()->except('page'));

        return [
            'products' => $products,
            'orderBy' => $orderBy,
            'sortBy' => $sortBy,
            'q' => $q,
            'perPage' => $perPage,
            'selectedCategoryId' => $categoryIdSelected
        ];
    }

    public function create()
    {
        $categories = Category::select('id', 'name')->get();

        return view('product.create', ['categories' => $categories]);
    }

    public function store(FieldRequestCreate $request)
    {
        $validationData = $request->validated();
        Product::create($validationData);

        return redirect('/products')->with('success', $request->name . ' is successfully create');
    }

    public function edit(Product $product)
    {
        $categories = Category::select('id', 'name')->get();

        return view('product.edit', ['product' => $product, 'categories' => $categories]);
    }

    public function update(FieldRequestUpdate $request, Product $product)
    {
        $product->update($request->all());

        return redirect('/products')->with('success',  $request->name . ' is successfully updated');
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect('/products')->with('success', 'Product is successfully deleted');
    }

    public function show()
    {
        $products = Product::all();
        return view('product.show', ['products' => $products]);
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="/products" style="margin-bottom: 1em">

        @csrf
        <div class="container">
            <div class="py-5 text-center">
                <img class="d-block mx-auto mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                <h2>Create product</h2>
            </div>

            <div class="row">

                <div class="col-md-10 order-md-1">
                    <form class="needs-validation" novalidate="">
                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="name">Name</label>
                                <input type="text" class="form-control {{$errors->has('name') ? 'is-danger' : ''}}" name="name"  value="{{old('name')}}">
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="status">Category</label>
                                <select class="form-control" name="category_id">
                                    <option  value=""></option>
                                    @foreach($categories as $category)
                                        <option  value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="size">Size</label>
                                <input type="text" class="form-control {{$errors->has('size') ? 'is-danger' : ''}}" name="size"  value="{{old('size')}}">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="price">Price</label>
                                <input type="text" class="form-control {{$errors->has('price') ? 'is-danger' : ''}}" name="price"  value="{{old('price')}}">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>

                        </div>

                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Add product</button>
                    </form>
                </div>
            </div>
        </div>
    </form>
    @include('errors')
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="/products/{{$product->id}}" style="margin-bottom: 1em">

        @csrf
        @method('PATCH')
        <div class="container">
            <div class="py-5 text-center">
                <img class="d-block mx-auto mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                <h2>Create product</h2>
            </div>

            <div class="row">

                <div class="col-md-10 order-md-1">
                    <form class="needs-validation" novalidate="">
                        <div class="row">
                            <div class="col-md-6 mb-6">
                                <label for="name">Name</label>
                                <input type="text" class="form-control {{$errors->has('name') ? 'is-danger' : ''}}" name="name"  value="{{$product->name}}">
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>

                            <div class="col-md-6 mb-3">
                                <label for="status">Category</label>
                                <select class="form-control" name="category_id">

                                    @foreach($categories as $category)
                                        <option  value="{{$category->id}}" {{$product->category_id == $category->id ? 'selected' : ''}} >{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="size">Size</label>
                                <input type="text" class="form-control {{$errors->has('size') ? 'is-danger' : ''}}" name="size"  value="{{$product->size}}">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="price">Price</label>
                                <input type="text" class="form-control {{$errors->has('price') ? 'is-danger' : ''}}" name="price"  value="{{$product->price}}">
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>

                        </div>

                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Edit product</button>
                    </form>
                </div>
            </div>
        </div>
    </form>
    @include('errors')
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    @include('success')
    <view-container>
        <view-head>
            <form action="{{ route('products') }}">
                <div class="row">
                    <div class="col-md-2" id="q">
                        <br>
                        <input class="form-control form-control-sm" type="search" name="q" value="{{ $q }}">
                    </div>
                    <div class="col-md-2 col-3">
                        Поле
                        <select name="sortBy" class="form-control form-control-sm" value="{{ $sortBy }}">
                            @foreach($sortable as $col)
                                <option @if($col == $sortBy) selected @endif value="{{ $col }}">{{ ucfirst($col) }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-md-2 col-3">
                        Сортировать по :
                        <select name="orderBy" class="form-control form-control-sm" value="{{ $orderBy }}">
                            @foreach(['asc', 'desc'] as $order)
                                <option @if($order == $orderBy) selected @endif value="{{ $order }}">{{ ucfirst($order) }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-md-2 col-3">
                        Количество записей:
                        <select name="perPage" class="form-control form-control-sm" value="{{ $perPage }}">
                            @foreach($countRecords as $page)
                                <option @if($page == $perPage) selected @endif value="{{ $page }}">{{ $page }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-2 col-3">
                        <br>
                        <button type="submit" class="btn btn-primary">Filter</button>
                    </div>
                </div>
                <br>
            <view-controls>
                <div style="min-width: 20ch;">
                    <h6>Filter by Category</h6>
                    <ul class="list-unstyled">

                        @foreach($categories as $category)
                        <li class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" name="category_id[]" class="form-check-input" {{in_array($category->id, $categoryIdSelected) ? 'checked' : ''}} value="{{$category->id}}">{{$category->id}}
                                <span>{{$category->name}}</span>
                            </label>
                        </li>

                        @endforeach

                    </ul>
                </div>
            </view-controls>
            </form>
        </view-head>


        <view-content>
            <h6>8 results</h6>
            <div class="card">
                    <div class="table-responsive">
                        @can('create products')
                            <button type="submit"><a href="/products/create">Add new product</a></button>
                        @endcan


                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>
                                    Category name</th>
                                <th>Name</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($products as $product)
                                <tr>
                                    <td>{{$product->id}}</td>
                                    <td>{{$product->category->name}}</td>
                                    <td>{{$product->name}}</td>
                                    <td>{{$product->size}}</td>
                                    <td>{{$product->price}}</td>
                                    <td>  <a href="/products/{{$product->id}}/edit">Edit</a></td>
                                    <td> <a href="/products/{{$product->id}}">Delete</a></td>
                                </tr>

                            @endforeach

                            </tbody>
                        </table>
                        <div class="clearfix">
                            {!! $products->links() !!}

                        </div>
                    </div>
                </div>
        </view-content>
    </view-container>

@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')

{{--    <div class="col-md-4 order-md-2 mb-4">--}}
{{--        <a href="/categories"><span>Go Back</span></a>--}}
{{--        <h4 class="d-flex justify-content-between align-items-center mb-3">--}}
{{--            <span class="text-muted">Selected products</span>--}}
{{--            <span class="badge badge-secondary badge-pill"> {{$products->count()}}</span>--}}
{{--        </h4>--}}
{{--    </div>--}}
{{--    <div class="col-md-12 products">--}}
{{--        <div class="row">--}}
{{--            <div class="container content">--}}
{{--                <div class="row">--}}
{{--                    --}}{{--            <div class="col-md-4">--}}
{{--                    --}}{{--                <div class="list-group">--}}
{{--                    --}}{{--                    <div class="list-group" id="myList" role="tablist">--}}
{{--                    --}}{{--                        <a class="list-group-item list-group-item-action active" data-toggle="list" href="#home" role="tab">Home</a>--}}
{{--                    --}}{{--                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#profile" role="tab">Profile</a>--}}
{{--                    --}}{{--                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#messages" role="tab">Messages</a>--}}
{{--                    --}}{{--                        <a class="list-group-item list-group-item-action" data-toggle="list" href="#settings" role="tab">Settings</a>--}}
{{--                    --}}{{--                    </div>--}}

{{--                    --}}{{--                </div>--}}
{{--                    --}}{{--            </div>--}}
{{--                    <div class="col-md-12 products">--}}
{{--                        <div class="row">--}}
{{--                            @foreach($products as $product)--}}
{{--                                <div class="col-sm-4">--}}
{{--                                    <div class="product">--}}
{{--                                        <div class="product-img">--}}
{{--                                            <a href="#"><img src="img/goods1.jpg" alt=""></a>--}}
{{--                                        </div>--}}
{{--                                        <p class="product-title">--}}
{{--                                            <a href="#">{{$product->name}}</a>--}}
{{--                                        </p>--}}
{{--                                        <p class="product-desc">{{$product->availability}}</p>--}}
{{--                                        <p class="product-price">Price: $ {{$product->price}}</p>--}}
{{--                                        <p class="product-size">Size: {{$product->size}}</p>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                            @endforeach--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
{{--    </div>--}}



@endsection